import type { Metadata, Viewport } from "next";
import {
  Barlow,
  Barlow_Condensed,
  Bellefair,
  Gabarito,
  Geist,
} from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/Header";

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1.0,
};

const bellefair = Bellefair({
  weight: ["400"],
  variable: "--font-bellefair",
  subsets: ["latin"],
});

const barlow = Barlow({
  weight: ["400"],
  variable: "--font-barlow",
  subsets: ["latin"],
});

const barlow_condensed = Barlow_Condensed({
  weight: ["400"],
  variable: "--font-barlow-condensed",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Space Tourism",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${bellefair.className} ${barlow.className} ${barlow_condensed.className} min-h-screen flex flex-col`}
      >
        <ThemeProvider attribute="class" forcedTheme="dark">
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
